// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrJD1nQQQ8duXTMGVp_NL29M739jlVGv4',
    appId: '1:666620707503:ios:57f45b75ec52248aac0a5a',
    messagingSenderId: '666620707503',
    projectId: 'studio-2888584615-2386e',
    storageBucket: 'studio-2888584615-2386e.firebasestorage.app',
    iosBundleId: 'com.example.bootstrapFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9qqzazlCShzrEI9wg3sZ66dvoP-4iRHA',
    appId: '1:666620707503:web:af971748d4d9342dac0a5a',
    messagingSenderId: '666620707503',
    projectId: 'studio-2888584615-2386e',
    authDomain: 'studio-2888584615-2386e.firebaseapp.com',
    storageBucket: 'studio-2888584615-2386e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qqzazlCShzrEI9wg3sZ66dvoP-4iRHA',
    appId: '1:666620707503:web:af971748d4d9342dac0a5a',
    messagingSenderId: '666620707503',
    projectId: 'studio-2888584615-2386e',
    authDomain: 'studio-2888584615-2386e.firebaseapp.com',
    storageBucket: 'studio-2888584615-2386e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrJD1nQQQ8duXTMGVp_NL29M739jlVGv4',
    appId: '1:666620707503:ios:57f45b75ec52248aac0a5a',
    messagingSenderId: '666620707503',
    projectId: 'studio-2888584615-2386e',
    storageBucket: 'studio-2888584615-2386e.firebasestorage.app',
    iosBundleId: 'com.example.bootstrapFlutter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb4lI2A8_1uBRYcuNvMntcBwdk8YSWxuQ',
    appId: '1:666620707503:android:1d14894ddc3889bbac0a5a',
    messagingSenderId: '666620707503',
    projectId: 'studio-2888584615-2386e',
    storageBucket: 'studio-2888584615-2386e.firebasestorage.app',
  );
}
