import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/widgets/app_icon.dart';

class AdminDashboardScreen extends StatefulWidget {
  const AdminDashboardScreen({super.key});
  @override State<AdminDashboardScreen> createState() => _AdminDashboardScreenState();
}

class _AdminDashboardScreenState extends State<AdminDashboardScreen> {
  int _tab = 0;
  static const _tabs = [('Dashboard', AppIcons.grid), ('Students', AppIcons.users), ('Learning', AppIcons.book), ('Support', AppIcons.support), ('Feedback', AppIcons.bulb), ('Analytics', AppIcons.chartBar), ('Settings', AppIcons.settings)];
  @override Widget build(BuildContext context) => Scaffold(
    backgroundColor: PennyPalColors.black,
    appBar: AppBar(backgroundColor: PennyPalColors.black, title: const Text('PennyPal Admin', style: TextStyle(color: PennyPalColors.white, fontWeight: FontWeight.w800)), actions: [IconButton(onPressed: () => context.go('/home'), icon: const AppIcon(AppIcons.logout, color: PennyPalColors.white, size: 18))]),
    body: Column(children: [
      SizedBox(height: 54, child: ListView.separated(scrollDirection: Axis.horizontal, padding: const EdgeInsets.symmetric(horizontal: 16), itemCount: _tabs.length, separatorBuilder: (_, __) => const SizedBox(width: 8), itemBuilder: (_, i) => ChoiceChip(label: Text(_tabs[i].$1), selected: _tab == i, onSelected: (_) => setState(() => _tab = i), selectedColor: PennyPalColors.white, labelStyle: TextStyle(color: _tab == i ? PennyPalColors.black : PennyPalColors.white)))),
      Expanded(child: _page()),
    ]),
  );
  Widget _page() => switch (_tab) {0 => const _Overview(), 1 => const _Records('userProfiles', 'Student Users', 'fullName', 'email'), 2 => const _Records('learningContent', 'Learning Content', 'title', 'category', editable: true), 3 => const _Records('supportQueries', 'Support Queries', 'subject', 'status', statusable: true), 4 => const _Records('feedback', 'Feedback', 'type', 'comment'), 5 => const _Analytics(), _ => const _Settings()};
}

class _Overview extends StatelessWidget { const _Overview(); @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.all(20), children: [const Text('Application overview', style: TextStyle(color: PennyPalColors.white, fontSize: 25, fontWeight: FontWeight.w800)), const SizedBox(height: 16), const Wrap(spacing: 12, runSpacing: 12, children: [_Count('Total Students', 'userProfiles'), _Count('Active Students', 'userProfiles'), _Count('Transactions', 'transactions'), _Count('Support Queries', 'supportQueries'), _Count('Feedback Received', 'feedback'), _Count('Learning Content', 'learningContent')]), const SizedBox(height: 28), const Text('Recent activity', style: TextStyle(color: PennyPalColors.white, fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 8), const Text('Monitor registrations, support and feedback below. Student financial records are only displayed as app-wide totals.', style: TextStyle(color: PennyPalColors.gray, height: 1.5))]); }
class _Count extends StatelessWidget { const _Count(this.label, this.collection); final String label, collection; @override Widget build(BuildContext context) => StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream: FirebaseFirestore.instance.collection(collection).snapshots(), builder: (_, s) => Container(width: 160, padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: PennyPalColors.surface, borderRadius: BorderRadius.circular(14), border: Border.all(color: PennyPalColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(s.hasData ? '${s.data!.size}' : '—', style: const TextStyle(color: PennyPalColors.white, fontSize: 25, fontWeight: FontWeight.w800)), const SizedBox(height: 6), Text(label, style: const TextStyle(color: PennyPalColors.gray, fontSize: 12))]))); }
class _Analytics extends StatelessWidget { const _Analytics(); @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.all(20), children: [const Text('Usage analytics', style: TextStyle(color:PennyPalColors.white,fontSize:25,fontWeight:FontWeight.w800)),const SizedBox(height:16),const Wrap(spacing:12,runSpacing:12,children:[_Count('Transactions recorded','transactions'),_Count('Budgets created','budgets'),_Count('Savings goals','savingsGoals'),_Count('AI assistant usage','aiUsage')]),const SizedBox(height:24),const Text('Analytics are aggregated to protect student financial privacy.',style:TextStyle(color:PennyPalColors.gray))]); }
class _Settings extends StatelessWidget { const _Settings(); @override Widget build(BuildContext context) => const Padding(padding: EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Admin settings',style:TextStyle(color:PennyPalColors.white,fontSize:25,fontWeight:FontWeight.w800)),SizedBox(height:14),Text('Administrators manage learning categories, notification preferences and access using Firebase. Only accounts with role = admin can open this dashboard.',style:TextStyle(color:PennyPalColors.gray,height:1.5))])); }
class _Records extends StatelessWidget { const _Records(this.collection,this.title,this.primary,this.secondary,{this.editable=false,this.statusable=false}); final String collection,title,primary,secondary; final bool editable,statusable; @override Widget build(BuildContext context) => StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection(collection).snapshots(),builder:(_,s){if(s.hasError)return Center(child:Text('Could not load $title: ${s.error}',style:const TextStyle(color:PennyPalColors.gray)));if(!s.hasData)return const Center(child:CircularProgressIndicator());final docs=s.data!.docs;return ListView(padding:const EdgeInsets.all(20),children:[Row(children:[Text(title,style:const TextStyle(color:PennyPalColors.white,fontSize:25,fontWeight:FontWeight.w800)),const Spacer(),if(editable)IconButton(onPressed:()=>_edit(context,null),icon:const AppIcon(AppIcons.add,color:PennyPalColors.white))]),const SizedBox(height:12),if(docs.isEmpty)const Text('No records yet.',style:TextStyle(color:PennyPalColors.gray)),for(final d in docs)Card(color:PennyPalColors.surface,child:ListTile(title:Text('${d.data()[primary]??'Untitled'}',style:const TextStyle(color:PennyPalColors.white)),subtitle:Text('${d.data()[secondary]??''}',style:const TextStyle(color:PennyPalColors.gray)),trailing:statusable?_statusMenu(d):editable?IconButton(onPressed:()=>_edit(context,d),icon:const AppIcon(AppIcons.edit,color:PennyPalColors.white,size:17)):null))]);});Widget _statusMenu(QueryDocumentSnapshot<Map<String,dynamic>> doc){final raw='${doc.data()['status']??'open'}'.toLowerCase();final status=['open','pending','resolved'].contains(raw)?raw:'open';return DropdownButton<String>(value:status,items:const[DropdownMenuItem(value:'open',child:Text('Open')),DropdownMenuItem(value:'pending',child:Text('Pending')),DropdownMenuItem(value:'resolved',child:Text('Resolved'))],onChanged:(v){if(v!=null)doc.reference.update({'status':v,'updatedAt':FieldValue.serverTimestamp()});});}Future<void> _edit(BuildContext context,DocumentSnapshot<Map<String,dynamic>>? doc)async{final c=TextEditingController(text:doc?.data()?[primary]??'');await showDialog(context:context,builder:(d)=>AlertDialog(title:Text(doc==null?'New content':'Edit content'),content:TextField(controller:c,decoration:InputDecoration(labelText:primary)),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancel')),TextButton(onPressed:()async{if(c.text.trim().isNotEmpty){final data={primary:c.text.trim(),'updatedAt':FieldValue.serverTimestamp()};if(doc==null){await FirebaseFirestore.instance.collection(collection).add({...data,'createdAt':FieldValue.serverTimestamp()});}else{await doc.reference.update(data);}}if(d.mounted)Navigator.pop(d);},child:const Text('Save'))]));}}
