import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../../../core/theme/app_theme.dart';

class AdminDashboardScreen extends StatefulWidget { const AdminDashboardScreen({super.key}); @override State<AdminDashboardScreen> createState()=>_AdminDashboardScreenState(); }
class _AdminDashboardScreenState extends State<AdminDashboardScreen> with SingleTickerProviderStateMixin { late TabController tabs; @override void initState(){super.initState();tabs=TabController(length:3,vsync:this);}@override void dispose(){tabs.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:PennyPalColors.black,appBar:AppBar(backgroundColor:PennyPalColors.black,title:const Text('Admin',style:TextStyle(color:Colors.white)),bottom:TabBar(controller:tabs,tabs:const[Tab(text:'Users'),Tab(text:'Learning'),Tab(text:'Support')]),actions:[IconButton(onPressed:()=>tabs.index==1?_contentDialog():null,icon:const Icon(Icons.add,color:Colors.white))]),body:TabBarView(controller:tabs,children:[_list('userProfiles',(d)=>ListTile(title:Text('${d['fullName']??'User'}',style:const TextStyle(color:Colors.white)),subtitle:Text('${d['email']??''}',style:const TextStyle(color:PennyPalColors.gray)))),_list('learningContent',(d)=>ListTile(onTap:()=>_contentDialog(d),title:Text('${d['title']??'Untitled'}',style:const TextStyle(color:Colors.white)),subtitle:Text('${d['category']??''}',style:const TextStyle(color:PennyPalColors.gray)),trailing:const Icon(Icons.edit,color:Colors.white))),_list('supportQueries',(d)=>ListTile(title:Text('${d['subject']??''}',style:const TextStyle(color:Colors.white)),subtitle:Text('${d['message']??''}',style:const TextStyle(color:PennyPalColors.gray)),trailing:Text('${d['status']??'open'}',style:const TextStyle(color:Colors.white))))]));
  Widget _list(String collection,Widget Function(Map<String,dynamic>) item)=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection(collection).snapshots(),builder:(_,s){if(s.hasError)return Center(child:Text('${s.error}',style:const TextStyle(color:Colors.white)));if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.docs.isEmpty)return const Center(child:Text('No records.',style:TextStyle(color:PennyPalColors.gray)));return ListView.separated(padding:const EdgeInsets.all(16),itemCount:s.data!.docs.length,separatorBuilder:(_,__)=>const Divider(color:PennyPalColors.border),itemBuilder:(_,i)=>item(s.data!.docs[i].data()));});
  Future<void> _contentDialog([Map<String,dynamic>? old])async{final title=TextEditingController(text:old?['title']??'');final category=TextEditingController(text:old?['category']??'');final summary=TextEditingController(text:old?['summary']??'');final content=TextEditingController(text:old?['content']??'');await showDialog(context:context,builder:(d)=>AlertDialog(title:Text(old==null?'New lesson':'Edit lesson'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Title')),TextField(controller:category,decoration:const InputDecoration(labelText:'Category')),TextField(controller:summary,decoration:const InputDecoration(labelText:'Summary')),TextField(controller:content,maxLines:5,decoration:const InputDecoration(labelText:'Content'))])),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancel')),TextButton(onPressed:()async{if(title.text.trim().isEmpty||content.text.trim().isEmpty)return;final data={'title':title.text.trim(),'category':category.text.trim(),'summary':summary.text.trim(),'content':content.text.trim(),'updatedAt':FieldValue.serverTimestamp()};await FirebaseFirestore.instance.collection('learningContent').add({...data,'createdAt':FieldValue.serverTimestamp()});if(d.mounted)Navigator.pop(d);},child:const Text('Publish'))]));}
}
